import Link from "next/link";

const steps = [
  {
    number: "1",
    title: "Tell us about you",
    description:
      "Share your degree, skills, interests, and the kinds of opportunities you want. Saved only on this device.",
  },
  {
    number: "2",
    title: "See what fits",
    description:
      "Browse internships, hackathons, competitions, workshops, and courses ranked by a clear compatibility score.",
  },
  {
    number: "3",
    title: "Read a short note",
    description:
      "When available, a short AI note explains why a listing is a strong, moderate, or light match — it never replaces the score.",
  },
];

const roadmap = [
  {
    title: "1-Click Application",
    description:
      "Direct placement portal connectivity so you can apply to verified listings without leaving StepAhead.",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.75"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
      >
        <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
        <polyline points="10 17 15 12 10 7" />
        <line x1="15" y1="12" x2="3" y2="12" />
      </svg>
    ),
  },
  {
    title: "Resume Auto-Parse",
    description:
      "Instant skill extraction from PDF uploads — drop your CV and your profile fills itself in seconds.",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.75"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
      >
        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
        <polyline points="14 2 14 8 20 8" />
        <line x1="16" y1="13" x2="8" y2="13" />
        <line x1="16" y1="17" x2="8" y2="17" />
        <line x1="10" y1="9" x2="8" y2="9" />
      </svg>
    ),
  },
  {
    title: "AI Mock Interviews",
    description:
      "Custom practice questions generated by Gemini for each bookmarked role, tailored to your skill gaps.",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.75"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
      >
        <path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z" />
      </svg>
    ),
  },
];

export default function Home() {
  return (
    <div className="min-h-screen bg-neutral-50 text-neutral-900 font-[family-name:var(--font-geist-sans)]">
      {/* ── Header ── */}
      <header className="mx-auto flex max-w-5xl items-center justify-between px-6 py-6">
        <Link
          href="/"
          className="flex items-center gap-2 text-xl font-bold tracking-tight text-slate-900"
        >
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="/favicon.ico"
            alt=""
            width={20}
            height={20}
            className="w-5 h-5 rounded-sm"
            aria-hidden="true"
          />
          StepAhead
        </Link>
        <Link
          href="/onboarding"
          className="text-sm font-medium text-neutral-600 transition-colors hover:text-indigo-600"
        >
          Get started
        </Link>
      </header>

      <main>
        {/* ── Hero ── */}
        <section className="mx-auto max-w-5xl px-6 py-16 sm:py-20">
          <p className="mb-4 text-sm font-medium uppercase tracking-wider text-indigo-600">
            For students
          </p>
          <h1 className="max-w-3xl text-4xl sm:text-5xl lg:text-5xl font-bold tracking-tight text-slate-900 leading-[1.15]">
            Find internships and opportunities that actually fit you.
          </h1>
          <p className="text-xl sm:text-2xl font-normal text-slate-600 max-w-2xl mt-4 leading-relaxed">
            Not another list of opportunities. Your list — matched to who you actually are.
          </p>
          <div className="mt-10">
            <Link
              href="/onboarding"
              className="inline-flex items-center justify-center rounded-lg bg-indigo-600 px-6 py-3 text-sm font-medium text-white shadow-sm transition-colors hover:bg-indigo-700"
            >
              Get Started
            </Link>
          </div>
        </section>

        {/* ── How it works ── */}
        <section className="border-t border-neutral-200 bg-white">
          <div className="mx-auto max-w-5xl px-6 py-20 sm:py-24">
            <h2 className="text-2xl font-semibold tracking-tight text-neutral-900">
              How it works
            </h2>
            <p className="mt-3 max-w-xl text-neutral-600">
              Three steps. Your profile stays in the browser.
            </p>
            <ol className="mt-12 grid gap-10 sm:grid-cols-3">
              {steps.map((step) => (
                <li key={step.number}>
                  <span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-indigo-50 text-sm font-semibold text-indigo-600">
                    {step.number}
                  </span>
                  <h3 className="mt-4 text-lg font-medium text-neutral-900">
                    {step.title}
                  </h3>
                  <p className="mt-2 text-sm leading-relaxed text-neutral-600">
                    {step.description}
                  </p>
                </li>
              ))}
            </ol>
          </div>
        </section>

        {/* ── The Future of Matching ── */}
        <section className="border-t border-neutral-200 bg-neutral-50">
          <div className="mx-auto max-w-5xl px-6 py-20 sm:py-24">
            <h2 className="text-2xl font-semibold tracking-tight text-neutral-900">
              The Future of Matching
            </h2>
            <p className="mt-3 max-w-xl text-sm text-neutral-500">
              Features in development — building toward a fully autonomous
              career co-pilot for students.
            </p>
            <div className="mt-10 grid gap-5 sm:grid-cols-3">
              {roadmap.map((item) => (
                <div
                  key={item.title}
                  className="rounded-xl border border-slate-200 bg-white p-6 flex flex-col gap-4"
                >
                  <span className="inline-flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600">
                    {item.icon}
                  </span>
                  <div>
                    <h3 className="text-sm font-semibold text-neutral-900">
                      {item.title}
                    </h3>
                    <p className="mt-1.5 text-sm leading-relaxed text-neutral-500">
                      {item.description}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
