"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";

const FAQS = [
  {
    q: "How is the compatibility score calculated?",
    a: "The score is deterministic and based on four signals: skill overlap (up to 40 points), interest overlap (up to 30 points), a match on your preferred opportunity type (+15), and a match on your preferred location or mode (+15). Scores are rounded to the nearest 5.",
  },
  {
    q: "Are the AI insights accurate?",
    a: "AI insights are generated by Google Gemini and are advisory only. They explain why an opportunity may or may not be a strong match for your profile. Always verify details directly on the opportunity's official page.",
  },
  {
    q: "How are opportunities verified?",
    a: 'Listings marked "Verified" link to real, publicly accessible opportunities. Listings marked "Seeded" are placeholder entries used to populate the feed during development — they are clearly labelled and not real openings.',
  },
  {
    q: "Is my profile data sent anywhere?",
    a: "Your profile is stored only in your browser's localStorage. It is sent to the server solely to compute AI match insights and is never stored, logged, or shared.",
  },
  {
    q: "Why do I see Remote opportunities from external sources?",
    a: "StepAhead pulls a small number of live remote tech listings from the Himalayas public API to supplement the curated seed data. These are labelled accordingly on each card.",
  },
];

export default function Footer() {
  const pathname = usePathname();

  return (
    <footer className="border-t border-neutral-200 bg-white font-[family-name:var(--font-geist-sans)]">
      {/* FAQ — only on the landing page. Component unmounts on navigation so
          accordion open-state resets automatically when leaving "/". */}
      {pathname === "/" && (
        <div className="mx-auto max-w-5xl px-6 pt-12 pb-8 mb-12">
          <h2 className="text-2xl font-semibold tracking-tight text-neutral-900">
            Frequently asked questions
          </h2>
          <p className="mt-1 text-sm text-neutral-500">
            Everything you need to know about how StepAhead works.
          </p>

          <dl className="mt-6 divide-y divide-neutral-100">
            {FAQS.map((faq) => (
              <details key={faq.q} className="group py-4">
                <summary className="flex cursor-pointer list-none items-start justify-between gap-4">
                  <dt className="text-sm font-medium text-neutral-900">
                    {faq.q}
                  </dt>
                  <span className="mt-0.5 shrink-0 text-neutral-400 transition-transform duration-200 group-open:rotate-180">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      aria-hidden="true"
                    >
                      <path d="m6 9 6 6 6-6" />
                    </svg>
                  </span>
                </summary>
                <dd className="mt-2 text-sm leading-relaxed text-slate-600">
                  {faq.a}
                </dd>
              </details>
            ))}
          </dl>
        </div>
      )}

      {/* Bottom bar — visible on every page */}
      <div className="border-t border-neutral-100">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
          {/* Left: favicon + brand name */}
          <div className="flex items-center gap-2">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/favicon.ico"
              alt=""
              width={16}
              height={16}
              className="w-4 h-4 rounded-sm"
              aria-hidden="true"
            />
            <span className="text-sm font-medium text-slate-500">StepAhead</span>
          </div>
          {/* Right: edit profile + attribution */}
          <div className="flex items-center gap-4 text-xs text-slate-400">
            <Link
              href="/onboarding"
              className="transition-colors hover:text-indigo-600"
            >
              Edit profile
            </Link>
            <span className="text-neutral-200">·</span>
            <span>
              Designed &amp; Developed by{" "}
              <span className="font-medium text-neutral-500">Ayesha Eman</span>
            </span>
          </div>
        </div>
      </div>
    </footer>
  );
}
